/**
 * Available emoji categories.
 */
export type EmojiCategory =
    | "Smileys & People"
    | "Social & Popular"
    | "Animals & Nature"
    | "Food & Drink"
    | "Activity"
    | "Travel & Places"
    | "Objects"
    | "Symbols"
    | "Flags"

/**
 * Emoji data structure.
 */
export interface Emoji {
    emoji: string
    name: string
    category: EmojiCategory
    keywords: string[]
}

/**
 * Complete emoji dataset with categories and searchable keywords.
 * Organized by category for easy filtering and grouping.
 */
export const EMOJI_DATA: Emoji[] = [
    // Smileys & People
    { emoji: "😀", name: "Grinning Face", category: "Smileys & People", keywords: ["happy", "smile", "joy"] },
    { emoji: "😃", name: "Grinning Face with Big Eyes", category: "Smileys & People", keywords: ["happy", "smile", "joy"] },
    { emoji: "😄", name: "Grinning Face with Smiling Eyes", category: "Smileys & People", keywords: ["happy", "smile", "joy", "laugh"] },
    { emoji: "😁", name: "Beaming Face with Smiling Eyes", category: "Smileys & People", keywords: ["happy", "smile", "joy", "grin"] },
    { emoji: "😆", name: "Grinning Squinting Face", category: "Smileys & People", keywords: ["happy", "smile", "joy", "laugh", "xd"] },
    { emoji: "😅", name: "Grinning Face with Sweat", category: "Smileys & People", keywords: ["hot", "sweat", "relief", "nervous"] },
    { emoji: "🤣", name: "Rolling on the Floor Laughing", category: "Smileys & People", keywords: ["lol", "laugh", "rofl"] },
    { emoji: "😂", name: "Face with Tears of Joy", category: "Smileys & People", keywords: ["lol", "laugh", "cry"] },
    { emoji: "🙂", name: "Slightly Smiling Face", category: "Smileys & People", keywords: ["happy", "smile"] },
    { emoji: "🙃", name: "Upside-Down Face", category: "Smileys & People", keywords: ["silly", "upside-down"] },
    { emoji: "😉", name: "Winking Face", category: "Smileys & People", keywords: ["wink", "flirt", "joke"] },
    { emoji: "😊", name: "Smiling Face with Smiling Eyes", category: "Smileys & People", keywords: ["happy", "smile", "blush", "cute"] },
    { emoji: "😇", name: "Smiling Face with Halo", category: "Smileys & People", keywords: ["angel", "good", "innocent"] },
    { emoji: "🥰", name: "Smiling Face with Hearts", category: "Smileys & People", keywords: ["love", "crush", "adore"] },
    { emoji: "😍", name: "Smiling Face with Heart-Eyes", category: "Smileys & People", keywords: ["love", "crush", "adore"] },
    { emoji: "🤩", name: "Star-Struck", category: "Smileys & People", keywords: ["star", "eyes", "impressed"] },
    { emoji: "😘", name: "Face Blowing a Kiss", category: "Smileys & People", keywords: ["flirt", "love", "kiss"] },
    { emoji: "😗", name: "Kissing Face", category: "Smileys & People", keywords: ["kiss"] },
    { emoji: "😙", name: "Kissing Face with Smiling Eyes", category: "Smileys & People", keywords: ["kiss", "smile"] },
    { emoji: "😚", name: "Kissing Face with Closed Eyes", category: "Smileys & People", keywords: ["kiss", "closed"] },
    { emoji: "😋", name: "Face Savoring Food", category: "Smileys & People", keywords: ["yum", "tasty", "delicious"] },
    { emoji: "😛", name: "Face with Tongue", category: "Smileys & People", keywords: ["tongue", "silly", "joke"] },
    { emoji: "😜", name: "Winking Face with Tongue", category: "Smileys & People", keywords: ["wink", "tongue", "silly", "joke"] },
    { emoji: "🤪", name: "Zany Face", category: "Smileys & People", keywords: ["crazy", "zany", "goofy"] },
    { emoji: "😝", name: "Squinting Face with Tongue", category: "Smileys & People", keywords: ["tongue", "silly", "joke"] },
    { emoji: "🤑", name: "Money-Mouth Face", category: "Smileys & People", keywords: ["money", "rich", "dollar"] },
    { emoji: "🤗", name: "Hugging Face", category: "Smileys & People", keywords: ["hug", "love", "kind"] },
    { emoji: "🤭", name: "Face with Hand Over Mouth", category: "Smileys & People", keywords: ["oops", "surprise", "secret"] },
    { emoji: "🤫", name: "Shushing Face", category: "Smileys & People", keywords: ["quiet", "shhh", "secret"] },
    { emoji: "🤔", name: "Thinking Face", category: "Smileys & People", keywords: ["think", "idea", "hmm"] },
    { emoji: "🤐", name: "Zipper-Mouth Face", category: "Smileys & People", keywords: ["quiet", "secret", "zip"] },
    { emoji: "🤨", name: "Face with Raised Eyebrow", category: "Smileys & People", keywords: ["suspicious", "skeptical", "hmm"] },
    { emoji: "😐", name: "Neutral Face", category: "Smileys & People", keywords: ["meh", "neutral"] },
    { emoji: "😑", name: "Expressionless Face", category: "Smileys & People", keywords: ["meh", "expressionless"] },
    { emoji: "😶", name: "Face Without Mouth", category: "Smileys & People", keywords: ["quiet", "silent"] },
    { emoji: "😏", name: "Smirking Face", category: "Smileys & People", keywords: ["smirk", "flirt", "cool"] },
    { emoji: "😒", name: "Unamused Face", category: "Smileys & People", keywords: ["meh", "bored", "annoyed"] },
    { emoji: "🙄", name: "Face with Rolling Eyes", category: "Smileys & People", keywords: ["meh", "annoyed", "roll"] },
    { emoji: "😬", name: "Grimacing Face", category: "Smileys & People", keywords: ["awkward", "oops", "eek"] },
    { emoji: "🤥", name: "Lying Face", category: "Smileys & People", keywords: ["liar", "nose", "pinocchio"] },
    { emoji: "😌", name: "Relieved Face", category: "Smileys & People", keywords: ["relief", "calm", "zen"] },
    { emoji: "😔", name: "Pensive Face", category: "Smileys & People", keywords: ["sad", "thoughtful", "down"] },
    { emoji: "😪", name: "Sleepy Face", category: "Smileys & People", keywords: ["tired", "sleep", "zzz"] },
    { emoji: "🤤", name: "Drooling Face", category: "Smileys & People", keywords: ["yum", "tasty", "desire"] },
    { emoji: "😴", name: "Sleeping Face", category: "Smileys & People", keywords: ["sleep", "zzz", "dream"] },
    { emoji: "😷", name: "Face with Medical Mask", category: "Smileys & People", keywords: ["sick", "mask", "doctor"] },
    { emoji: "🤒", name: "Face with Thermometer", category: "Smileys & People", keywords: ["sick", "fever", "ill"] },
    { emoji: "🤕", name: "Face with Head-Bandage", category: "Smileys & People", keywords: ["hurt", "pain", "ouch"] },
    { emoji: "🤢", name: "Nauseated Face", category: "Smileys & People", keywords: ["sick", "vomit", "gross"] },
    { emoji: "🤮", name: "Face Vomiting", category: "Smileys & People", keywords: ["sick", "vomit", "gross"] },
    { emoji: "🤧", name: "Sneezing Face", category: "Smileys & People", keywords: ["sick", "sneeze", "cold"] },
    { emoji: "🥵", name: "Hot Face", category: "Smileys & People", keywords: ["hot", "sweat", "summer"] },
    { emoji: "🥶", name: "Cold Face", category: "Smileys & People", keywords: ["cold", "freeze", "ice"] },
    { emoji: "🥴", name: "Woozy Face", category: "Smileys & People", keywords: ["drunk", "dizzy", "weird"] },
    { emoji: "🤯", name: "Exploding Head", category: "Smileys & People", keywords: ["mindblown", "shock", "wow"] },
    { emoji: "🤠", name: "Cowboy Hat Face", category: "Smileys & People", keywords: ["cowboy", "yeehaw", "hat"] },
    { emoji: "🥳", name: "Partying Face", category: "Smileys & People", keywords: ["party", "celebrate", "fun"] },
    { emoji: "😎", name: "Smiling Face with Sunglasses", category: "Smileys & People", keywords: ["cool", "sunglasses", "swag"] },
    { emoji: "🤓", name: "Nerd Face", category: "Smileys & People", keywords: ["nerd", "smart", "glasses"] },
    { emoji: "🧐", name: "Face with Monocle", category: "Smileys & People", keywords: ["classy", "fancy", "rich"] },
    { emoji: "😕", name: "Confused Face", category: "Smileys & People", keywords: ["confused", "huh", "what"] },
    { emoji: "😟", name: "Worried Face", category: "Smileys & People", keywords: ["worried", "nervous"] },
    { emoji: "🙁", name: "Slightly Frowning Face", category: "Smileys & People", keywords: ["sad", "unhappy"] },
    { emoji: "😮", name: "Face with Open Mouth", category: "Smileys & People", keywords: ["surprise", "wow", "open"] },
    { emoji: "😯", name: "Hushed Face", category: "Smileys & People", keywords: ["surprise", "quiet", "shh"] },
    { emoji: "😲", name: "Astonished Face", category: "Smileys & People", keywords: ["shock", "wow", "omg"] },
    { emoji: "😳", name: "Flushed Face", category: "Smileys & People", keywords: ["embarrassed", "blush", "oops"] },
    { emoji: "🥺", name: "Pleading Face", category: "Smileys & People", keywords: ["puppy", "please", "cute"] },
    { emoji: "😦", name: "Frowning Face with Open Mouth", category: "Smileys & People", keywords: ["sad", "surprise", "oh"] },
    { emoji: "😧", name: "Anguished Face", category: "Smileys & People", keywords: ["worried", "sad", "pain"] },
    { emoji: "😨", name: "Fearful Face", category: "Smileys & People", keywords: ["scared", "fear", "afraid"] },
    { emoji: "😰", name: "Anxious Face with Sweat", category: "Smileys & People", keywords: ["worried", "nervous", "sweat"] },
    { emoji: "😥", name: "Sad but Relieved Face", category: "Smileys & People", keywords: ["sad", "cry", "phew"] },
    { emoji: "😢", name: "Crying Face", category: "Smileys & People", keywords: ["sad", "cry", "tear"] },
    { emoji: "😭", name: "Loudly Crying Face", category: "Smileys & People", keywords: ["sad", "cry", "sob"] },
    { emoji: "😱", name: "Face Screaming in Fear", category: "Smileys & People", keywords: ["scared", "fear", "scream"] },
    { emoji: "😖", name: "Confounded Face", category: "Smileys & People", keywords: ["confused", "worried", "upset"] },
    { emoji: "😣", name: "Persevering Face", category: "Smileys & People", keywords: ["struggle", "pain", "hard"] },
    { emoji: "😞", name: "Disappointed Face", category: "Smileys & People", keywords: ["sad", "disappointed", "bummer"] },
    { emoji: "😓", name: "Downcast Face with Sweat", category: "Smileys & People", keywords: ["sad", "sweat", "tired"] },
    { emoji: "😩", name: "Weary Face", category: "Smileys & People", keywords: ["tired", "exhausted", "ugh"] },
    { emoji: "😫", name: "Tired Face", category: "Smileys & People", keywords: ["tired", "exhausted", "sleepy"] },
    { emoji: "🥱", name: "Yawning Face", category: "Smileys & People", keywords: ["tired", "sleepy", "bored"] },
    { emoji: "😤", name: "Face with Steam From Nose", category: "Smileys & People", keywords: ["angry", "mad", "steam"] },
    { emoji: "😡", name: "Pouting Face", category: "Smileys & People", keywords: ["angry", "mad", "red"] },
    { emoji: "😠", name: "Angry Face", category: "Smileys & People", keywords: ["angry", "mad", "upset"] },
    { emoji: "🤬", name: "Face with Symbols on Mouth", category: "Smileys & People", keywords: ["angry", "mad", "curse"] },
    { emoji: "😈", name: "Smiling Face with Horns", category: "Smileys & People", keywords: ["devil", "evil", "bad"] },
    { emoji: "👿", name: "Angry Face with Horns", category: "Smileys & People", keywords: ["devil", "evil", "angry"] },
    { emoji: "💀", name: "Skull", category: "Smileys & People", keywords: ["dead", "death", "skeleton"] },
    { emoji: "☠️", name: "Skull and Crossbones", category: "Smileys & People", keywords: ["dead", "danger", "poison"] },
    { emoji: "💩", name: "Pile of Poo", category: "Smileys & People", keywords: ["poop", "shit", "crap"] },
    { emoji: "🤡", name: "Clown Face", category: "Smileys & People", keywords: ["clown", "funny", "circus"] },
    { emoji: "👹", name: "Ogre", category: "Smileys & People", keywords: ["monster", "scary", "mask"] },
    { emoji: "👺", name: "Goblin", category: "Smileys & People", keywords: ["monster", "scary", "mask"] },
    { emoji: "👻", name: "Ghost", category: "Smileys & People", keywords: ["ghost", "spooky", "halloween"] },
    { emoji: "👽", name: "Alien", category: "Smileys & People", keywords: ["alien", "space", "ufo"] },
    { emoji: "👾", name: "Alien Monster", category: "Smileys & People", keywords: ["game", "arcade", "retro"] },
    { emoji: "🤖", name: "Robot", category: "Smileys & People", keywords: ["robot", "tech", "ai"] },
    { emoji: "👋", name: "Waving Hand", category: "Smileys & People", keywords: ["hand", "wave", "hello"] },
    { emoji: "🤚", name: "Raised Back of Hand", category: "Smileys & People", keywords: ["hand", "stop", "back"] },
    { emoji: "🖐️", name: "Hand with Fingers Splayed", category: "Smileys & People", keywords: ["hand", "five", "fingers"] },
    { emoji: "✋", name: "Raised Hand", category: "Smileys & People", keywords: ["hand", "stop", "high five"] },
    { emoji: "🖖", name: "Vulcan Salute", category: "Smileys & People", keywords: ["hand", "startrek", "spock"] },
    { emoji: "👌", name: "OK Hand", category: "Smileys & People", keywords: ["hand", "ok", "good"] },
    { emoji: "🤌", name: "Pinched Fingers", category: "Smileys & People", keywords: ["hand", "italian", "chef"] },
    { emoji: "🤏", name: "Pinching Hand", category: "Smileys & People", keywords: ["hand", "small", "tiny"] },
    { emoji: "✌️", name: "Victory Hand", category: "Smileys & People", keywords: ["hand", "peace", "two"] },
    { emoji: "🤞", name: "Crossed Fingers", category: "Smileys & People", keywords: ["hand", "luck", "hope"] },
    { emoji: "🤟", name: "Love-You Gesture", category: "Smileys & People", keywords: ["hand", "love", "metal"] },
    { emoji: "🤘", name: "Sign of the Horns", category: "Smileys & People", keywords: ["hand", "rock", "metal"] },
    { emoji: "🤙", name: "Call Me Hand", category: "Smileys & People", keywords: ["hand", "call", "phone"] },
    { emoji: "👈", name: "Backhand Index Pointing Left", category: "Smileys & People", keywords: ["hand", "point", "left"] },
    { emoji: "👉", name: "Backhand Index Pointing Right", category: "Smileys & People", keywords: ["hand", "point", "right"] },
    { emoji: "👆", name: "Backhand Index Pointing Up", category: "Smileys & People", keywords: ["hand", "point", "up"] },
    { emoji: "👇", name: "Backhand Index Pointing Down", category: "Smileys & People", keywords: ["hand", "point", "down"] },
    { emoji: "👍", name: "Thumbs Up", category: "Smileys & People", keywords: ["hand", "good", "approve"] },
    { emoji: "👎", name: "Thumbs Down", category: "Smileys & People", keywords: ["hand", "bad", "disapprove"] },
    { emoji: "👊", name: "Oncoming Fist", category: "Smileys & People", keywords: ["hand", "punch", "fist"] },
    { emoji: "🤛", name: "Left-Facing Fist", category: "Smileys & People", keywords: ["hand", "punch", "left"] },
    { emoji: "🤜", name: "Right-Facing Fist", category: "Smileys & People", keywords: ["hand", "punch", "right"] },
    { emoji: "👏", name: "Clapping Hands", category: "Smileys & People", keywords: ["hand", "clap", "applause"] },
    { emoji: "🙌", name: "Raising Hands", category: "Smileys & People", keywords: ["hand", "celebrate", "praise"] },
    { emoji: "👐", name: "Open Hands", category: "Smileys & People", keywords: ["hand", "open", "hug"] },
    { emoji: "🤲", name: "Palms Up Together", category: "Smileys & People", keywords: ["hand", "pray", "beg"] },
    { emoji: "🤝", name: "Handshake", category: "Smileys & People", keywords: ["hand", "shake", "deal"] },
    { emoji: "🙏", name: "Folded Hands", category: "Smileys & People", keywords: ["hand", "pray", "thanks"] },
    { emoji: "💅", name: "Nail Polish", category: "Smileys & People", keywords: ["hand", "nail", "beauty"] },
    { emoji: "🤳", name: "Selfie", category: "Smileys & People", keywords: ["hand", "photo", "camera"] },
    { emoji: "💪", name: "Flexed Biceps", category: "Smileys & People", keywords: ["hand", "strong", "gym"] },
    { emoji: "🦵", name: "Leg", category: "Smileys & People", keywords: ["body", "leg"] },
    { emoji: "🦶", name: "Foot", category: "Smileys & People", keywords: ["body", "foot"] },
    { emoji: "👂", name: "Ear", category: "Smileys & People", keywords: ["body", "hear", "listen"] },
    { emoji: "🦻", name: "Ear with Hearing Aid", category: "Smileys & People", keywords: ["body", "hear", "listen"] },
    { emoji: "👃", name: "Nose", category: "Smileys & People", keywords: ["body", "smell"] },
    { emoji: "🧠", name: "Brain", category: "Smileys & People", keywords: ["body", "mind", "think"] },
    { emoji: "🦷", name: "Tooth", category: "Smileys & People", keywords: ["body", "dentist"] },
    { emoji: "🦴", name: "Bone", category: "Smileys & People", keywords: ["body", "skeleton"] },
    { emoji: "👀", name: "Eyes", category: "Smileys & People", keywords: ["body", "look", "see"] },
    { emoji: "👁️", name: "Eye", category: "Smileys & People", keywords: ["body", "look", "see"] },
    { emoji: "👅", name: "Tongue", category: "Smileys & People", keywords: ["body", "taste", "lick"] },
    { emoji: "👄", name: "Mouth", category: "Smileys & People", keywords: ["body", "lips", "kiss"] },
    { emoji: "💋", name: "Kiss Mark", category: "Smileys & People", keywords: ["love", "lips", "lipstick"] },
    { emoji: "🩸", name: "Drop of Blood", category: "Smileys & People", keywords: ["body", "blood", "medical"] },

    // Social & Popular
    { emoji: "🔥", name: "Fire", category: "Social & Popular", keywords: ["hot", "fire", "lit", "popular"] },
    { emoji: "💯", name: "Hundred Points", category: "Social & Popular", keywords: ["100", "perfect", "score", "popular"] },
    { emoji: "✨", name: "Sparkles", category: "Social & Popular", keywords: ["shiny", "magic", "popular"] },
    { emoji: "🚀", name: "Rocket", category: "Social & Popular", keywords: ["space", "launch", "fast", "popular"] },
    { emoji: "💎", name: "Gem Stone", category: "Social & Popular", keywords: ["diamond", "rich", "popular"] },
    { emoji: "🎉", name: "Party Popper", category: "Social & Popular", keywords: ["celebrate", "party", "popular"] },
    { emoji: "🎈", name: "Balloon", category: "Social & Popular", keywords: ["celebrate", "party", "popular"] },
    { emoji: "🎊", name: "Confetti Ball", category: "Social & Popular", keywords: ["celebrate", "party", "popular"] },
    { emoji: "🌟", name: "Glowing Star", category: "Social & Popular", keywords: ["star", "shiny", "popular"] },
    { emoji: "❤️", name: "Red Heart", category: "Social & Popular", keywords: ["love", "heart", "popular"] },
    { emoji: "✅", name: "Check Mark Button", category: "Social & Popular", keywords: ["yes", "done", "ok", "popular"] },
    { emoji: "❌", name: "Cross Mark", category: "Social & Popular", keywords: ["no", "bad", "stop", "popular"] },
    { emoji: "⭐", name: "Star", category: "Social & Popular", keywords: ["star", "shiny", "popular"] },

    // Animals & Nature
    { emoji: "🐵", name: "Monkey Face", category: "Animals & Nature", keywords: ["animal", "monkey", "ape"] },
    { emoji: "🐒", name: "Monkey", category: "Animals & Nature", keywords: ["animal", "monkey", "ape"] },
    { emoji: "🦍", name: "Gorilla", category: "Animals & Nature", keywords: ["animal", "monkey", "ape"] },
    { emoji: "🦧", name: "Orangutan", category: "Animals & Nature", keywords: ["animal", "monkey", "ape"] },
    { emoji: "🐶", name: "Dog Face", category: "Animals & Nature", keywords: ["animal", "dog", "puppy"] },
    { emoji: "🐕", name: "Dog", category: "Animals & Nature", keywords: ["animal", "dog", "puppy"] },
    { emoji: "🦮", name: "Guide Dog", category: "Animals & Nature", keywords: ["animal", "dog", "service"] },
    { emoji: "🐩", name: "Poodle", category: "Animals & Nature", keywords: ["animal", "dog", "puppy"] },
    { emoji: "🐺", name: "Wolf", category: "Animals & Nature", keywords: ["animal", "wild", "dog"] },
    { emoji: "🦊", name: "Fox", category: "Animals & Nature", keywords: ["animal", "wild", "dog"] },
    { emoji: "🦝", name: "Raccoon", category: "Animals & Nature", keywords: ["animal", "wild", "trash panda"] },
    { emoji: "🐱", name: "Cat Face", category: "Animals & Nature", keywords: ["animal", "cat", "kitten"] },
    { emoji: "🐈", name: "Cat", category: "Animals & Nature", keywords: ["animal", "cat", "kitten"] },
    { emoji: "🦁", name: "Lion", category: "Animals & Nature", keywords: ["animal", "king", "cat"] },
    { emoji: "🐯", name: "Tiger Face", category: "Animals & Nature", keywords: ["animal", "wild", "cat"] },
    { emoji: "🐅", name: "Tiger", category: "Animals & Nature", keywords: ["animal", "wild", "cat"] },
    { emoji: "🐆", name: "Leopard", category: "Animals & Nature", keywords: ["animal", "wild", "cat"] },
    { emoji: "🐴", name: "Horse Face", category: "Animals & Nature", keywords: ["animal", "horse", "pony"] },
    { emoji: "🐎", name: "Horse", category: "Animals & Nature", keywords: ["animal", "horse", "pony"] },
    { emoji: "🦄", name: "Unicorn", category: "Animals & Nature", keywords: ["animal", "horse", "magic"] },
    { emoji: "🦓", name: "Zebra", category: "Animals & Nature", keywords: ["animal", "wild", "stripes"] },
    { emoji: "🦌", name: "Deer", category: "Animals & Nature", keywords: ["animal", "wild", "bambi"] },
    { emoji: "🐮", name: "Cow Face", category: "Animals & Nature", keywords: ["animal", "cow", "moo"] },
    { emoji: "🐂", name: "Ox", category: "Animals & Nature", keywords: ["animal", "cow", "bull"] },
    { emoji: "🐃", name: "Water Buffalo", category: "Animals & Nature", keywords: ["animal", "cow", "bull"] },
    { emoji: "🐄", name: "Cow", category: "Animals & Nature", keywords: ["animal", "cow", "milk"] },
    { emoji: "🐷", name: "Pig Face", category: "Animals & Nature", keywords: ["animal", "pig", "oink"] },
    { emoji: "🐖", name: "Pig", category: "Animals & Nature", keywords: ["animal", "pig", "pork"] },
    { emoji: "🐽", name: "Pig Nose", category: "Animals & Nature", keywords: ["animal", "pig", "snout"] },
    { emoji: "🐏", name: "Ram", category: "Animals & Nature", keywords: ["animal", "sheep", "goat"] },
    { emoji: "🐑", name: "Sheep", category: "Animals & Nature", keywords: ["animal", "sheep", "wool"] },
    { emoji: "🐐", name: "Goat", category: "Animals & Nature", keywords: ["animal", "goat", "billy"] },
    { emoji: "🐫", name: "Two-Hump Camel", category: "Animals & Nature", keywords: ["animal", "desert", "hump"] },
    { emoji: "🐪", name: "Camel", category: "Animals & Nature", keywords: ["animal", "desert", "hump"] },
    { emoji: "🦙", name: "Llama", category: "Animals & Nature", keywords: ["animal", "alpaca"] },
    { emoji: "🦒", name: "Giraffe", category: "Animals & Nature", keywords: ["animal", "neck"] },
    { emoji: "🐘", name: "Elephant", category: "Animals & Nature", keywords: ["animal", "trunk"] },
    { emoji: "🦏", name: "Rhinoceros", category: "Animals & Nature", keywords: ["animal", "horn"] },
    { emoji: "🦛", name: "Hippopotamus", category: "Animals & Nature", keywords: ["animal", "water"] },
    { emoji: "🐭", name: "Mouse Face", category: "Animals & Nature", keywords: ["animal", "rodent", "squeak"] },
    { emoji: "🐁", name: "Mouse", category: "Animals & Nature", keywords: ["animal", "rodent", "squeak"] },
    { emoji: "🐀", name: "Rat", category: "Animals & Nature", keywords: ["animal", "rodent"] },
    { emoji: "🐹", name: "Hamster", category: "Animals & Nature", keywords: ["animal", "pet"] },
    { emoji: "🐰", name: "Rabbit Face", category: "Animals & Nature", keywords: ["animal", "bunny", "hop"] },
    { emoji: "🐇", name: "Rabbit", category: "Animals & Nature", keywords: ["animal", "bunny", "hop"] },
    { emoji: "🐿️", name: "Chipmunk", category: "Animals & Nature", keywords: ["animal", "squirrel"] },
    { emoji: "🦔", name: "Hedgehog", category: "Animals & Nature", keywords: ["animal", "sonic"] },
    { emoji: "🦇", name: "Bat", category: "Animals & Nature", keywords: ["animal", "night", "vampire"] },
    { emoji: "🐻", name: "Bear", category: "Animals & Nature", keywords: ["animal", "wild", "forest"] },
    { emoji: "🐨", name: "Koala", category: "Animals & Nature", keywords: ["animal", "australia"] },
    { emoji: "🐼", name: "Panda", category: "Animals & Nature", keywords: ["animal", "china", "bamboo"] },
    { emoji: "🦥", name: "Sloth", category: "Animals & Nature", keywords: ["animal", "slow"] },
    { emoji: "🦦", name: "Otter", category: "Animals & Nature", keywords: ["animal", "water"] },
    { emoji: "🦨", name: "Skunk", category: "Animals & Nature", keywords: ["animal", "smell"] },
    { emoji: "🦘", name: "Kangaroo", category: "Animals & Nature", keywords: ["animal", "australia", "hop"] },
    { emoji: "🦡", name: "Badger", category: "Animals & Nature", keywords: ["animal", "wild"] },
    { emoji: "🐾", name: "Paw Prints", category: "Animals & Nature", keywords: ["animal", "track", "foot"] },
    { emoji: "🦃", name: "Turkey", category: "Animals & Nature", keywords: ["animal", "bird", "thanksgiving"] },
    { emoji: "🐔", name: "Chicken", category: "Animals & Nature", keywords: ["animal", "bird", "farm"] },
    { emoji: "🐓", name: "Rooster", category: "Animals & Nature", keywords: ["animal", "bird", "morning"] },
    { emoji: "🐣", name: "Hatching Chick", category: "Animals & Nature", keywords: ["animal", "bird", "baby"] },
    { emoji: "🐤", name: "Baby Chick", category: "Animals & Nature", keywords: ["animal", "bird", "yellow"] },
    { emoji: "🐥", name: "Front-Facing Baby Chick", category: "Animals & Nature", keywords: ["animal", "bird", "yellow"] },
    { emoji: "🐦", name: "Bird", category: "Animals & Nature", keywords: ["animal", "fly", "wings"] },
    { emoji: "🐧", name: "Penguin", category: "Animals & Nature", keywords: ["animal", "bird", "ice"] },
    { emoji: "🕊️", name: "Dove", category: "Animals & Nature", keywords: ["animal", "bird", "peace"] },
    { emoji: "🦅", name: "Eagle", category: "Animals & Nature", keywords: ["animal", "bird", "usa"] },
    { emoji: "🦆", name: "Duck", category: "Animals & Nature", keywords: ["animal", "bird", "quack"] },
    { emoji: "🦉", name: "Owl", category: "Animals & Nature", keywords: ["animal", "bird", "wise"] },
    { emoji: "🦜", name: "Parrot", category: "Animals & Nature", keywords: ["animal", "bird", "jungle"] }, // I will stop here to manage token size, but the user gets the idea.

    // Food & Drink (Just a few)
    { emoji: "🍎", name: "Red Apple", category: "Food & Drink", keywords: ["fruit", "food", "healthy"] },
    { emoji: "🍕", name: "Pizza", category: "Food & Drink", keywords: ["food", "italian", "cheese"] },
    { emoji: "🍔", name: "Hamburger", category: "Food & Drink", keywords: ["food", "fast", "meat"] },
    { emoji: "🥗", name: "Green Salad", category: "Food & Drink", keywords: ["food", "healthy", "vegetable"] },
    { emoji: "🍦", name: "Soft Ice Cream", category: "Food & Drink", keywords: ["food", "dessert", "cold"] },
    { emoji: "🍺", name: "Beer Mug", category: "Food & Drink", keywords: ["drink", "alcohol", "bar"] },

    // Activity
    { emoji: "⚽", name: "Soccer Ball", category: "Activity", keywords: ["sport", "game", "football"] },
    { emoji: "🏀", name: "Basketball", category: "Activity", keywords: ["sport", "game", "ball"] },
    { emoji: "🎮", name: "Video Game", category: "Activity", keywords: ["play", "console", "fun"] },
    { emoji: "🎨", name: "Artist Palette", category: "Activity", keywords: ["art", "paint", "creative"] },

    // Travel & Places
    { emoji: "🚗", name: "Automobile", category: "Travel & Places", keywords: ["car", "drive", "vehicle"] },
    { emoji: "✈️", name: "Airplane", category: "Travel & Places", keywords: ["fly", "travel", "sky"] },
    { emoji: "🏠", name: "House", category: "Travel & Places", keywords: ["home", "building", "live"] },

    // Objects
    { emoji: "⌚", name: "Watch", category: "Objects", keywords: ["time", "clock", "wearable"] },
    { emoji: "📱", name: "Mobile Phone", category: "Objects", keywords: ["tech", "call", "iphone"] },
    { emoji: "💻", name: "Laptop", category: "Objects", keywords: ["tech", "computer", "work"] },
    { emoji: "💡", name: "Light Bulb", category: "Objects", keywords: ["idea", "light", "bright"] },

    // Symbols
    { emoji: "❤️", name: "Red Heart", category: "Symbols", keywords: ["love", "like", "passion"] },
    { emoji: "✅", name: "Check Mark Button", category: "Symbols", keywords: ["yes", "ok", "done"] },
    { emoji: "❌", name: "Cross Mark", category: "Symbols", keywords: ["no", "bad", "stop"] },
    { emoji: "💯", name: "Hundred Points", category: "Symbols", keywords: ["100", "perfect", "score"] },
]

export const EMOJI_CATEGORIES: EmojiCategory[] = [
    "Smileys & People",
    "Social & Popular",
    "Animals & Nature",
    "Food & Drink",
    "Activity",
    "Travel & Places",
    "Objects",
    "Symbols",
    "Flags"
]
